"""empty message

Revision ID: 2cf0a268e413
Revises: 6a44581da922
Create Date: 2021-04-26 16:50:09.717227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf0a268e413'
down_revision = '6a44581da922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'user')
    # ### end Alembic commands ###
